approve_by_comment: true
approve_regex: ^(Approved|approved|:\+1:|\+1|LGTM|lgtm)
reject_regex: ^Rejected
reset_on_push: true
author_approval: ignored
reviewers:
  members:
  - aaronkl
  - KEggensperger
  - mfeurer
  - mlindauer
  - sfalkner
  required: 2