language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
    - python: "2.7"

cache:
  directories:
    - $HOME/.cache/pip
  pip: true

sudo: false

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
addons:
  sources:
    # necessary for rfr 
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
  apt:
    packages:
    # necessary for rfr
    - gcc-4.8
    - g++-4.8
    - libatlas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy>=1.6.1 scipy>=0.13.1 six nose matplotlib setuptools Cython
  - pip install pep8 python-coveralls
  - pip install coverage
  - pip install psutil
  # necessary for rfr
  - export CXX="g++-4.8" CC="gcc-4.8"
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - nosetests -sv --with-coverage
after_success:
  - coveralls
